config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  resources :trainers do
    post :add_pokemon
    post '/remove_pokemon/:trainer_pokemon_id', to: 'trainers#remove_pokemon', as: 'remove_pokemon' 
  end
  resources :pokedexes
  resources :pokemons do
    get :new_details, on: :new
    post :add_skill
    get :heal
    post '/remove_skill/:pokemon_skill_id', to: 'pokemons#remove_skill', as: 'remove_skill'
    collection do
      get :heal_all
    end
  end
  
  resources :skills
  resources :pokemon_battles, only: [:index, :show, :new, :create] do
    get :auto_battle
    get :evolution_confirmation
    get :choose_skill
    post :submit_skill
    post :evolve
    post :action
    resources :pokemon_battle_logs, only: :index
  end
end

app/models/pokemon_battle.rb
class PokemonBattle < ApplicationRecord
	extend Enumerize

	ONGOING_STATE = 'ongoing'.freeze
	FINISH_STATE = 'finish'.freeze
	STATE_LIST = [ ONGOING_STATE, FINISH_STATE ]

	AUTO_BATTLE_TYPE = 'auto'.freeze
	MANUAL_BATTLE_TYPE = 'manual'.freeze
	VERSUS_AI_BATTLE_TYPE = 'versus ai'.freeze
	BATTLE_TYPE_LIST = [ AUTO_BATTLE_TYPE, MANUAL_BATTLE_TYPE, VERSUS_AI_BATTLE_TYPE ]
	
	belongs_to :pokemon1, class_name: 'Pokemon',
												foreign_key: 'pokemon1_id'
	belongs_to :pokemon2, class_name: 'Pokemon',
												foreign_key: 'pokemon2_id'
	belongs_to :pokemon_winner, class_name: 'Pokemon',
												foreign_key: 'pokemon_winner_id',
												optional: true
	belongs_to :pokemon_loser, class_name: 'Pokemon',
												foreign_key: 'pokemon_loser_id',
												optional: true
	has_many :pokemon_battle_logs, dependent: :destroy

	enumerize :state, in: STATE_LIST
	enumerize :battle_type, in: BATTLE_TYPE_LIST

	validates :pokemon1_id, presence: true
	validates :pokemon2_id, presence: true
	validates :current_turn, presence: true,
										numericality: { greater_than: 0 }
	validates :state, presence: true,
					 					length: { maximum: 45 }
	validates :experience_gain, numericality: { only_integer: true }, if: :experience_gain_present?
	validates :pokemon1_max_health_point, presence: true,
										numericality: { greater_than: 0 }
	validates :pokemon2_max_health_point, presence: true,
										numericality: { greater_than: 0 }
	validates :battle_type, presence: true,
					 					length: { maximum: 45 }

	validate :pokemon1_and_pokemon2_must_not_same, if: :pokemon_1_and_pokemon_2_same?, on: :create
	validate :pokemon_still_on_batlle, unless: :pokemon_1_and_pokemon_2_same?, on: :create
	validate :pokemon_must_not_fainted, on: :create

	def pokemon1_and_pokemon2_must_not_same		
		errors.add(:pokemon2, "must not be same as Pokemon1")
	end

	def pokemon_still_on_batlle
		pokemon_id_with_ongoing_battle = PokemonBattle.where(state: ONGOING_STATE)
																		 							.pluck(:pokemon1_id, :pokemon2_id)
																		 							.flatten
																		 							.uniq
		
		errors.add(:pokemon1, "still on battle") if pokemon_id_with_ongoing_battle.include?(pokemon1_id)		
		errors.add(:pokemon2, "still on battle") if pokemon_id_with_ongoing_battle.include?(pokemon2_id)
	end

	def pokemon_1_and_pokemon_2_same?
		pokemon1_id == pokemon2_id
	end

	def pokemon_must_not_fainted
		if pokemon1_id.present? && pokemon2_id.present?
			errors.add(:pokemon1, "must not fainted") if pokemon1.current_health_point == 0
			errors.add(:pokemon2, "must not fainted") if pokemon2.current_health_point == 0
		end
	end

	def experience_gain_present?
		experience_gain.present?
	end
end

app/controllers/pokemon_battles_controller.rb
class PokemonBattlesController < ApplicationController

	add_breadcrumb "Pokemon Battles", :pokemon_battles_path

	def index
		decorator = PokemonBattlesDecorator.new(self)
		@decorated_pokemon_battles = decorator.decorate_for_index(PokemonBattle.paginate(page: params[:page], per_page: 10).order(id: :ASC))
		@pagination_pokemon_battles = PokemonBattle.paginate(page: params[:page], per_page: 10).order(id: :ASC)
	end

	def show
		decorator = PokemonBattlesDecorator.new(self)
		@decorated_pokemon_battle = decorator.decorate_for_show(PokemonBattle.find(params[:id]))
		@errors = {skill: '', action_type: ''}
		add_breadcrumb "#{@decorated_pokemon_battle.pokemon1.name} vs #{@decorated_pokemon_battle.pokemon2.name}"
	end

	def new
		@pokemon_battle = PokemonBattle.new
		add_breadcrumb 'New'
	end

	def action
		pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		pokemon_skill = (params[:pokemon_skill_id].present?) ? PokemonSkill.find(params[:pokemon_skill_id]) : PokemonSkill.new()

		battle_engine = BattleEngine.new(pokemon_battle)

		if battle_engine.valid_next_turn?(pokemon_skill: pokemon_skill, action_type: params[:action_type])
			ActiveRecord::Base.transaction do
				battle_engine.next_turn!(pokemon_skill)
				battle_engine.save!
				if(pokemon_battle.battle_type == PokemonBattle::VERSUS_AI_BATTLE_TYPE)
					auto_battle_engine = AutoBattleEngine.new(pokemon_battle: pokemon_battle)
					auto_battle_engine.execute_enemy_ai(battle_engine)
				end
			end

			if pokemon_battle.state == PokemonBattle::FINISH_STATE && PokemonEvolution.able_to_evolve?(pokemon_battle.pokemon_winner)
				redirect_to pokemon_battle_evolution_confirmation_path(pokemon_battle.id)
			else
				redirect_to pokemon_battle
			end
		else
			@errors = battle_engine.errors
			decorator = PokemonBattlesDecorator.new(self)
			@decorated_pokemon_battle = decorator.decorate_for_show(pokemon_battle)
			render 'show'
		end
	end

	def evolution_confirmation
		@pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
	end

	def evolve
		pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		if params[:confirmation] == PokemonEvolution::YES
			PokemonEvolution.evolve!(pokemon_battle.pokemon_winner)
			redirect_to pokemon_battle_choose_skill_path(pokemon_battle.id)
		else
			redirect_to pokemon_battle
		end
	end

	def choose_skill
		@pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		@pokemon_skills = PokemonSkill.where(pokemon_id: @pokemon_battle.pokemon_winner.id)
		@errors = {skill_to_add: '', skill_to_remove: ''}
	end

	def submit_skill
		@errors = {skill_to_add: '', skill_to_remove: ''}
		@pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		@pokemon_skills = PokemonSkill.where(pokemon_id: @pokemon_battle.pokemon_winner.id)
		if params[:submit_action] == 'cancel'
			redirect_to @pokemon_battle
		else
			if params[:skill_to_add].present?
				skill_to_add = Skill.find_by(id: params[:skill_to_add])
				if params[:skill_to_remove].present? && @pokemon_skills.count == 4
					skill_to_remove = PokemonSkill.find(params[:skill_to_remove])
					PokemonEvolution.add_skill_after_evolve(
						pokemon: @pokemon_battle.pokemon_winner,
						skill_to_add: skill_to_add,
						skill_to_remove: skill_to_remove
					)
					redirect_to @pokemon_battle
				elsif !params[:skill_to_remove].present? && @pokemon_skills.count == 4
					@errors[:skill_to_remove] = 'must be chosen'
					render 'choose_skill'
				else
					PokemonEvolution.add_skill_after_evolve(pokemon: @pokemon_battle.pokemon_winner, skill_to_add: skill_to_add)
					redirect_to @pokemon_battle
				end
			else
				@errors[:skill_to_add] = 'must be chosen'
				render 'choose_skill'
			end
		end
	end

	def auto_battle
		pokemon_battle = PokemonBattle.find(params[:pokemon_battle_id])
		pokemon_battle.battle_type = PokemonBattle::AUTO_BATTLE_TYPE
		pokemon_battle.save
			
		ActiveRecord::Base.transaction do
			auto_battle_engine = AutoBattleEngine.new(pokemon_battle: pokemon_battle)
			auto_battle_engine.execute
		end

		if pokemon_battle.state == PokemonBattle::FINISH_STATE && PokemonEvolution.able_to_evolve?(pokemon_battle.pokemon_winner)
			redirect_to pokemon_battle_evolution_confirmation_path(pokemon_battle.id)
		else
			redirect_to pokemon_battle
		end
	end

	def create
		@pokemon_battle = PokemonBattle.new(pokemon_battle_params)
		@pokemon_battle.state = PokemonBattle::ONGOING_STATE
		@pokemon_battle.current_turn = 1
		@pokemon_battle.battle_type = params[:battle_type]

		@pokemon_battle.pokemon1_max_health_point = Pokemon.find(params[:pokemon_battle][:pokemon1_id]).max_health_point if params[:pokemon_battle][:pokemon1_id].present?
		@pokemon_battle.pokemon2_max_health_point = Pokemon.find(params[:pokemon_battle][:pokemon2_id]).max_health_point if params[:pokemon_battle][:pokemon2_id].present?

		if @pokemon_battle.save
			if @pokemon_battle.battle_type == PokemonBattle::AUTO_BATTLE_TYPE
				redirect_to pokemon_battle_auto_battle_path(@pokemon_battle.id)
			else
				redirect_to @pokemon_battle
			end
		else
			render 'new'
		end
	end

	private
		def pokemon_battle_params
			params.require(:pokemon_battle).permit(:pokemon1_id, :pokemon2_id)
		end
end

app/helpers/pokemon_battles_helper.rb
module PokemonBattlesHelper
end

app/views/pokemon_battles/choose_skill.html.erb
<div class="col-sm-offset-4 col-sm-4">
	<div class="panel panel-primary">
		<div class="panel-heading">New skill for <%= @pokemon_battle.pokemon_winner.name %></div>
		<div class="panel-body">
			<div class="col-sm-12">
				<%= form_tag(pokemon_battle_submit_skill_path(@pokemon_battle.id), enforce_utf8: false) do %>
					<% if @pokemon_skills.count == 4 %>
						<div class="form-group <%= 'has-error' if @errors[:skill_to_remove].present? %>">
							<%= label_tag :skill_to_remove %>
			    		<%= select_tag :skill_to_remove, options_for_select(@pokemon_skills.collect{ |pokemon_skill| [pokemon_skill.skill.name, pokemon_skill.id] }, '-- Select --'), {prompt: '-- Select --', class: 'form-control'} %>
			    		<p class="error-message"><%= @errors[:skill_to_remove] %></p>
			    	</div>
			    <% end %>
		    	<div class="form-group <%= 'has-error' if @errors[:skill_to_add].present? %>">
						<%= label_tag :skill_to_add %>
		    		<%= select_tag :skill_to_add, options_for_select(Skill.all.collect{ |skill| [skill.name, skill.id] }, '-- Select --'), {prompt: '-- Select --', class: 'form-control'} %>
		    		<p class="error-message"><%= @errors[:skill_to_add] %></p>
		    	</div>
		    	<div class="text-center">
						<%= submit_tag :submit, { name: 'submit_action', class: 'btn btn-primary' } %>
						<%= submit_tag :cancel, { name: 'submit_action', class: 'btn btn-primary' } %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/pokemon_battles/evolution_confirmation.html.erb
<% if @pokemon_battle.state == PokemonBattle::FINISH_STATE && PokemonEvolution.able_to_evolve?(@pokemon_battle.pokemon_winner) %>

<div class="col-sm-offset-4 col-sm-4">
	<div class="panel panel-primary">
		<div class="panel-heading">Do you want to evolve <%= @pokemon_battle.pokemon_winner.name %>?</div>
		<div class="panel-body">
			<div class="col-sm-offset-2 col-sm-8 text-center">
				<%= form_for @pokemon_battle, url: pokemon_battle_evolve_path(@pokemon_battle.id), method: :post do |f| %>
					<%= f.submit PokemonEvolution::YES, { name: 'confirmation', class: 'btn btn-primary' } %>
					<%= f.submit PokemonEvolution::NO, { name: 'confirmation', class: 'btn btn-primary' } %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/pokemon_battles/index.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Pokemon Battles</div>
	<div class="panel-body">
		<div class="action-container">
			<a href="<%= new_pokemon_battle_path %>" class="btn btn-primary">New</a>
		</div>
		<div class="col-xs-12 table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<td>#</td>
						<td>Pokemon 1</td>
						<td>Pokemon 2</td>
						<td>Current Turn</td>
						<td>State</td>
						<td>Winner</td>
						<td>Loser</td>
						<td>Experience Gain</td>
						<td>Action</td>
					</tr>
				</thead>
				<tbody>
					<% @decorated_pokemon_battles.each_with_index do |pokemon_battle, index| %>
						<%	if params[:page].to_i > 0 
									@current_page = (params[:page].to_i - 1) * 10 + index + 1
								else
									@current_page = params[:page].to_i * 10 + index + 1
								end
						%>
						<tr>
							<td><%= @current_page %></td>
							<td><%= pokemon_battle.link_to_show_with_pokemon1_name %></td>
							<td><%= pokemon_battle.link_to_show_with_pokemon2_name %></td>
							<td><%= pokemon_battle.current_turn %></td>
							<td><%= pokemon_battle.state %></td>
							<td><%= pokemon_battle.pokemon_winner %></td>
							<td><%= pokemon_battle.pokemon_loser %></td>
							<td><%= pokemon_battle.experience_gain %></td>
							<td><%= pokemon_battle.link_to_log %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<div class="text-center flickr_pagination">
				<%= will_paginate @pagination_pokemon_battles %>
			</div>
		</div>
	</div>
</div>

app/views/pokemon_battles/new.html.erb
<div class="col-sm-offset-1 col-sm-10">
	<div class="panel panel-primary">
		<div class="panel-heading">New Pokemon Battle</div>
		<div class="panel-body">
		<%= form_for @pokemon_battle do |f| %>
			<%= render 'layouts/error_message', error_object: @pokemon_battle.errors %>
			<div class="form-group col-sm-5 <%= 'has-error' if @pokemon_battle.errors.include?(:pokemon1) %>">
				<%= f.label :pokemon1_id %>
				<%= f.select :pokemon1_id, options_for_select(Pokemon.where('current_health_point > 0').order(id: :ASC).collect{ |pokemon| [pokemon.name, pokemon.id] }), {prompt: "-- Select --"}, {class: 'form-control'} %>
				<p class="error-message"><%= @pokemon_battle.errors.messages[:pokemon1].join(' and ') %></p>
			</div>
			<div class="form-group col-sm-2 text-center">
				<%= label_tag :vs, 'VS' %>
			</div>
			<div class="form-group col-sm-5 <%= 'has-error' if @pokemon_battle.errors.include?(:pokemon2) %>">
				<%= f.label :pokemon2_id %>
				<%= f.select :pokemon2_id, options_for_select(Pokemon.where('current_health_point > 0').order(id: :ASC).collect{ |pokemon| [pokemon.name, pokemon.id] }), {prompt: "-- Select --"}, {class: 'form-control'} %>
				<p class="error-message"><%= @pokemon_battle.errors.messages[:pokemon2].join(' and ') %></p>
			</div>
			<%= f.hidden_field :state, value: PokemonBattle::ONGOING_STATE %>
			<%= f.hidden_field :current_turn, value: 1 %>
			<div class="form-group col-sm-12 text-center">
				<p>Start Battle!</p>
				<%= f.submit PokemonBattle::AUTO_BATTLE_TYPE, { name: 'battle_type', class: 'btn btn-primary' } %>
				<%= f.submit PokemonBattle::MANUAL_BATTLE_TYPE, { name: 'battle_type', class: 'btn btn-primary' } %>
				<%= f.submit PokemonBattle::VERSUS_AI_BATTLE_TYPE, { name: 'battle_type', class: 'btn btn-primary' } %>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/pokemon_battles/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Pokemon Battle</div>
	<div class="panel-body">
		<div class="col-xs-12 action-container">
			<%= @decorated_pokemon_battle.link_to_log %>
			<%=
				if @decorated_pokemon_battle.state == PokemonBattle::ONGOING_STATE
					if @decorated_pokemon_battle.pokemon1_available_skills.present? && @decorated_pokemon_battle.pokemon2_available_skills.present?
						@decorated_pokemon_battle.link_to_auto_battle
					end
				end
			%>
		</div>

		<div class="col-xs-12  <%= 'alert alert-danger' if @errors[:action_type].present? %>">
			<h3 class="text-center"><%= @errors[:action_type] %></h3>
		</div>

		<% if @decorated_pokemon_battle.pokemon_winner.present? %>
			<div class="col-xs-12">
				<h3 class="text-center">Winner : <%= @decorated_pokemon_battle.pokemon_winner %></h3>
			</div>
		<% end %>

		<div class="col-xs-12">
			<div class="col-sm-5">
				<h3 class="text-center"><%= @decorated_pokemon_battle.pokemon1.link_to_show %></h3>
				<h4 class="text-center">HP : <%= @decorated_pokemon_battle.pokemon1_current_health_point %></h4>
			</div>

			<div class="col-sm-2">
				<h3 class="text-center">VS</h3>
				<h5 class="text-center"><%= @decorated_pokemon_battle.state %></h5>
			</div>

			<div class="col-sm-5">
				<h3 class="text-center"><%= @decorated_pokemon_battle.pokemon2.link_to_show %></h3>
				<h4 class="text-center">HP : <%= @decorated_pokemon_battle.pokemon2_current_health_point %></h4>
			</div>
		</div>

		<div class="col-xs-12">
			<div class="col-sm-5">
				<div class="col-xs-12 img-container">
					<%= @decorated_pokemon_battle.pokemon1.image %>	
				</div>
				
				<% if @decorated_pokemon_battle.state == PokemonBattle::ONGOING_STATE && @decorated_pokemon_battle.current_turn.odd? %>
					<div class="col-xs-12 action">
						<%= form_tag(pokemon_battle_action_path(@decorated_pokemon_battle.id), enforce_utf8: false) do %>
							<% if @decorated_pokemon_battle.pokemon1_available_skills.count > 0 %>
								<div class="form-group <%= 'has-error' if @errors[:skill].present? %>">
									<%= label_tag :pokemon_skill_id, 'Attack skill' %>
									<%= select_tag :pokemon_skill_id, options_for_select(@decorated_pokemon_battle.pokemon1_available_skills.collect{ |pokemon_skill| [pokemon_skill.skill.name, pokemon_skill.id] }, "-- Select --"), { prompt: '-- Select --', class: 'form-control'} %>
									<p class="error-message"><%= @errors[:skill] %></p>
								</div>
								<%= submit_tag PokemonBattleLog::ATTACK_ACTION, { name: 'action_type', class: 'btn btn-primary' } %>
							<% end %>
							<%= submit_tag PokemonBattleLog::SURRENDER_ACTION, { name: 'action_type', class: 'btn btn-primary' } %>
						<% end %>
					</div>
				<% end %>
			</div>

			<div class="col-sm-2">
			</div>

			<div class="col-sm-5">
				<div class="col-xs-12 img-container">
					<%= @decorated_pokemon_battle.pokemon2.image %>	
				</div>
				
				<% if @decorated_pokemon_battle.state == PokemonBattle::ONGOING_STATE && !@decorated_pokemon_battle.current_turn.odd? %>
					<div class="col-xs-12 action">
						<%= form_tag(pokemon_battle_action_path(@decorated_pokemon_battle.id), enforce_utf8: false) do %>
							<% if @decorated_pokemon_battle.pokemon2_available_skills.count > 0 %>
								<div class="form-group <%= 'has-error' if @errors[:skill].present? %>">
									<%= label_tag :pokemon_skill_id, 'Attack skill' %>
									<%= select_tag :pokemon_skill_id, options_for_select(@decorated_pokemon_battle.pokemon2_available_skills.collect{ |pokemon_skill| [pokemon_skill.skill.name, pokemon_skill.id] }, "-- Select --"), { prompt: '-- Select --', class: 'form-control'} %>
									<p class="error-message"><%= @errors[:skill] %></p>
								</div>
								<%= submit_tag PokemonBattleLog::ATTACK_ACTION, { name: 'action_type', class: 'btn btn-primary' } %>
							<% end %>
							<%= submit_tag PokemonBattleLog::SURRENDER_ACTION, { name: 'action_type', class: 'btn btn-primary' } %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>