config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  resources :trainers do
    post :add_pokemon
    post '/remove_pokemon/:trainer_pokemon_id', to: 'trainers#remove_pokemon', as: 'remove_pokemon' 
  end
  resources :pokedexes
  resources :pokemons do
    get :new_details, on: :new
    post :add_skill
    get :heal
    post '/remove_skill/:pokemon_skill_id', to: 'pokemons#remove_skill', as: 'remove_skill'
    collection do
      get :heal_all
    end
  end
  
  resources :skills
  resources :pokemon_battles, only: [:index, :show, :new, :create] do
    get :auto_battle
    get :evolution_confirmation
    get :choose_skill
    post :submit_skill
    post :evolve
    post :action
    resources :pokemon_battle_logs, only: :index
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	belongs_to :pokedex
	has_many :pokemon_battle_pokemon1, class_name: 'PokemonBattle', foreign_key: 'pokemon1_id', dependent: :destroy
	has_many :pokemon_battle_pokemon2, class_name: 'PokemonBattle', foreign_key: 'pokemon2_id', dependent: :destroy
	has_many :pokemon_battle_pokemon_winner, class_name: 'PokemonBattle', foreign_key: 'pokemon_winner_id', dependent: :destroy
	has_many :pokemon_battle_pokemon_loser, class_name: 'PokemonBattle', foreign_key: 'pokemon_loser_id', dependent: :destroy
	has_many :pokemon_skills, dependent: :destroy
	has_many :skills, through: :pokemon_skills
	has_one :trainer_pokemon, dependent: :destroy
	has_one :trainer, through: :trainer_pokemon

	validates :pokedex_id, presence: true
	validates :name, presence: true, uniqueness: true,
					 								length: { maximum: 45 }
	validates :current_health_point, presence: true,
										numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: :max_health_point }, if: :max_health_point_present?
	validates :max_health_point, presence: true,
										numericality: { greater_than: 0 }
	validates :attack, presence: true,
										numericality: { greater_than: 0 }
	validates :defence, presence: true,
										numericality: { greater_than: 0 }
	validates :speed, presence: true,
										numericality: { greater_than: 0 }
	validates :level, presence: true,
										numericality: { greater_than: 0 }
	validates :current_experience, presence: true,
										numericality: { greater_than_or_equal_to: 0 }

	def max_health_point_present?
		max_health_point.present?
	end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
	add_breadcrumb "Pokemons", :pokemons_path

	def index
		decorator = PokemonsDecorator.new(self)
		@decorated_pokemons = decorator.decorate_for_index(Pokemon.paginate(page: params[:page], per_page: 10).order(id: :ASC))
		@pagination_pokemons = Pokemon.paginate(page: params[:page], per_page: 10).order(id: :ASC)
	end

	def show
		decorator = PokemonsDecorator.new(self)
		@decorated_pokemon = decorator.decorate_for_show(Pokemon.find(params[:id]))
		@pokemon_skill = PokemonSkill.new
		add_breadcrumb @decorated_pokemon.name
	end

	def new
		@pokemon = Pokemon.new
		add_breadcrumb 'New'
	end

	def new_details
		pokedex = Pokedex.find(params[:q])
		@pokemon = Pokemon.new(pokedex: pokedex, name: pokedex.name, level: 1, current_health_point: pokedex.base_health_point, max_health_point: pokedex.base_health_point, attack: pokedex.base_attack, defence: pokedex.base_defence, speed: pokedex.base_speed, current_experience: 0)
		add_breadcrumb 'New', :new_pokemon_path
		add_breadcrumb 'Details'
	end

	def add_skill
		pokemon = Pokemon.find(params[:pokemon_id])
		skill = Skill.find_by(id: params[:pokemon_skill][:skill_id])
		@pokemon_skill = PokemonSkill.new(pokemon: pokemon, skill: skill, current_pp: params[:pokemon_skill][:current_pp])

		decorator = PokemonsDecorator.new(self)
		@decorated_pokemon = decorator.decorate_for_show(pokemon)

		if @pokemon_skill.save
			redirect_to pokemon
		else
			render 'show'
		end
	end

	def heal
		pokemon = Pokemon.find(params[:pokemon_id])

		ActiveRecord::Base.transaction do
			pokemon.current_health_point = pokemon.max_health_point
			pokemon.pokemon_skills.each do |pokemon_skill|
				pokemon_skill.current_pp = pokemon_skill.skill.max_pp
				pokemon_skill.save
			end
			pokemon.save
		end

		redirect_to pokemon
	end

	def heal_all
		pokemon_id_with_ongoing_battle = PokemonBattle.where(state: PokemonBattle::ONGOING_STATE)
																			 							.pluck(:pokemon1_id, :pokemon2_id)
																			 							.flatten
																			 							.uniq

		pokemons = Pokemon.where.not(id: pokemon_id_with_ongoing_battle)
		pokemon_skills = PokemonSkill.includes(:skill).where.not(pokemon_id: pokemon_id_with_ongoing_battle)
		ActiveRecord::Base.transaction do
			pokemons.update_all('current_health_point = max_health_point')
			pokemon_skills.each do |pokemon_skill|
				pokemon_skill.current_pp = pokemon_skill.skill.max_pp
			end
			pokemon_skills.each(&:save)
		end
		redirect_to pokemons_path
	end

	def edit
		@pokemon = Pokemon.find(params[:id])
		add_breadcrumb @pokemon.name, @pokemon
		add_breadcrumb 'Edit'
	end

	def create
		@pokemon = Pokemon.new(pokemon_params)

		if @pokemon.save
			redirect_to @pokemon
		else
			render 'new_details'
		end
	end

	def update
		@pokemon = Pokemon.find(params[:id])

		if @pokemon.update(pokemon_params)
			redirect_to @pokemon
		else
			render 'edit'
		end
	end

	def destroy
		@pokemon = Pokemon.find(params[:id])
		@pokemon.destroy

		redirect_to pokemons_path
	end

	def remove_skill
		PokemonSkill.find(params[:pokemon_skill_id])
								.destroy

		redirect_to pokemon_path(params[:pokemon_id])
	end

	private
		def pokemon_params
			params.require(:pokemon).permit(:pokedex_id, :name, :level, :max_health_point, :current_health_point, :attack, :defence, :speed, :current_experience)
		end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<div class="panel-body">
	<div class="col-sm-offset-2 col-sm-8">
		<%= form_for @pokemon do |f| %>
			<%= render 'layouts/error_message', error_object: @pokemon.errors %>
			<%= f.hidden_field :pokedex_id, value: @pokemon.pokedex.id %>
			<div class="form-group">
				<%= label_tag :pokedex %>
				<div>
					<%= label_tag :pokedex_name, "#{@pokemon.pokedex.name}" %>
				</div>
			</div>
			<div class="form-group">
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:name) %>">
				<%= f.label :name %>
	    	<%= f.text_field :name, class: 'form-control' %>
				<p class="error-message"><%= @pokemon.errors.messages[:name].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:level) %>">
				<%= f.label :level %>
	    	<%= f.text_field :level, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:level].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:current_health_point) %>">
				<%= f.label :current_health_point %>
	    	<%= f.text_field :current_health_point, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:current_health_point].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:max_health_point) %>">
				<%= f.label :max_health_point %>
	    	<%= f.text_field :max_health_point, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:max_health_point].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:attack) %>">
				<%= f.label :attack %>
	    	<%= f.text_field :attack, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:attack].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:defence) %>">
				<%= f.label :defence %>
	    	<%= f.text_field :defence, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:defence].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:speed) %>">
				<%= f.label :speed %>
	    	<%= f.text_field :speed, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:speed].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @pokemon.errors.include?(:current_experience) %>">
				<%= f.label :current_experience %>
	    	<%= f.text_field :current_experience, class: 'form-control' %>
	    	<p class="error-message"><%= @pokemon.errors.messages[:pokedex_id].join(' and ') %></p>
			</div>
			<%= f.submit yield(:submit_text), class: 'btn btn-primary center-block' %>
		<% end %>
	</div>
</div>

app/views/pokemons/edit.html.erb
<% provide(:submit_text, 'Update') %>

<div class="panel panel-primary">
	<div class="panel-heading">Edit Pokemon</div>
	<%= render 'pokemons/form' %>
</div>

app/views/pokemons/index.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Pokemons</div>
	<div class="panel-body">
		<div class="action-container">
			<a href="<%= new_pokemon_path %>" class="btn btn-primary">New</a>
			<a href="<%= heal_all_pokemons_path %>" class="btn btn-success">Heal All</a>
		</div>
		
		<div class="col-xs-12 table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<td>#</td>
						<td>Name</td>
						<td>Level</td>
						<td>Health Point</td>
						<td>Attack</td>
						<td>Defence</td>
						<td>Speed</td>
						<td>Current Experience</td>
						<td>Image</td>
					</tr>
				</thead>
				<tbody>
					<%	if params[:page].to_i > 0 
								@current_page = (params[:page].to_i - 1) * 10
							else
								@current_page = params[:page].to_i * 10
							end
					%>
					<% @decorated_pokemons.each_with_index do |pokemon, index| %>
						<tr>
							<td><%= @current_page + index + 1 %></td>
							<td><%= pokemon.link_to_show %></td>
							<td><%= pokemon.level %></td>
							<td><%= pokemon.current_health_point %></td>
							<td><%= pokemon.attack %></td>
							<td><%= pokemon.defence %></td>
							<td><%= pokemon.speed %></td>
							<td><%= pokemon.current_experience %></td>
							<td><%= pokemon.image_small %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<div class="text-center flickr_pagination">
				<%= will_paginate @pagination_pokemons %>
			</div>
		</div>
	</div>
</div>

app/views/pokemons/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
	<div class="panel panel-primary">
		<div class="panel-heading">New Pokemon</div>
		<div class="panel-body">
			<%= form_tag(new_details_new_pokemon_path, method: 'get', enforce_utf8: false) do %>
				<div class="form-group">
					<%= label_tag :Pokedex %>
					<%= select_tag :q, options_for_select(Pokedex.all.collect{ |pokedex| [pokedex.name, pokedex.id] }, "-- Select --"), { prompt: '-- Select --', class: 'form-control', required: true} %>
				</div>
				<%= submit_tag :submit, class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/pokemons/new_details.html.erb
<% provide(:submit_text, 'Create') %>

<div class="panel panel-primary">
	<div class="panel-heading">New Pokemon Details</div>
	<%= render 'pokemons/form' %>
</div>

app/views/pokemons/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Pokemon</div>
	<div class="panel-body">
		<div class="col-sm-12 action-container">
			<a href="<%= new_pokemon_path %>" class="btn btn-primary">New</a>
			<%= @decorated_pokemon.link_to_heal if @decorated_pokemon.not_in_battle %>
			<%= @decorated_pokemon.link_to_edit if @decorated_pokemon.not_in_battle %>
			<%= @decorated_pokemon.link_to_delete %>
		</div>

		<div class="col-sm-offset-1 col-sm-10 col-xs-12 col-md-offset-2 col-md-8">
			<div class="row center-block">
				<div class="col-sm-6 col-xs-12">
					<%= @decorated_pokemon.image %>	
				</div>

				<div class="col-sm-6 col-xs-12">
					<table align="center">
						<tr>
							<td>Name</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.name %></td>
						</tr>
						<tr>
							<td>Level</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.level %></td>
						</tr>
						<tr>
							<td>Health point</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.current_health_point %></td>
						</tr>
						<tr>
							<td>Attack</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.attack %></td>
						</tr>
						<tr>
							<td>Defence</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.defence %></td>
						</tr>
						<tr>
							<td>Speed</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.speed %></td>
						</tr>
						<tr>
							<td>Current experience</td>
							<td>&nbsp;:&nbsp;</td>
							<td><%= @decorated_pokemon.current_experience %></td>
						</tr>
					</table>
				</div>
			</div>
		</div>


		<div class="container col-sm-12">
			<div class="row">
				<h4>Skills</h4>
			</div>
			<div class="row">
				<table class="table table-hover">
					<thead>
						<tr>
							<td>Name</td>
							<td>Current PP</td>
							<% if @decorated_pokemon.not_in_battle %>
								<td align="right">Action</td>
							<% end %>
						</tr>
					</thead>
					<tbody>
						<% @decorated_pokemon.pokemon_skills.each do |pokemon_skill| %>
							<tr>
								<td><%= pokemon_skill.skill.name %></td>
								<td><%= pokemon_skill.current_pp %></td>
								<% if @decorated_pokemon.not_in_battle %>
									<td align="right"><%= link_to 'Remove', pokemon_remove_skill_path(@decorated_pokemon.id, pokemon_skill.id),
										method: :post, 
										data: { confirm: "Are you sure to remove #{pokemon_skill.skill.name}?"}, class: 'btn btn-danger' %></td>
								<% end %>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>

		<% if @decorated_pokemon.not_in_battle %>
			<div class="container col-sm-12">
				<h4>Add New Skill</h4>
				<%= form_for @pokemon_skill, url: pokemon_add_skill_path(@decorated_pokemon.id) do |f| %>
					<%= render 'layouts/error_message', error_object: @pokemon_skill.errors %>
					<div class="col-sm-6 form-group <%= 'has-error' if @pokemon_skill.errors.include?(:skill_id) %>">
						<%= f.label :skill_id %>
						<%= f.select :skill_id, options_for_select(Skill.all.collect{ |skill| [skill.name, skill.id] }), { prompt: '-- Select --'}, {class: 'form-control'} %>
			    	<p class="error-message"><%= @pokemon_skill.errors.messages[:skill_id].join(' and ') %></p>
					</div>
					<div class="col-sm-6 form-group <%= 'has-error' if @pokemon_skill.errors.include?(:current_pp) %>">
						<%= f.label :current_pp %>
						<%= f.text_field :current_pp, class: 'form-control' %>
			    	<p class="error-message"><%= @pokemon_skill.errors.messages[:current_pp].join(' and ') %></p>
					</div>
					<div class="col-sm-12 form-group">
						<%= f.submit :submit, class: 'btn btn-primary' %>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>