config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  resources :trainers do
    post :add_pokemon
    post '/remove_pokemon/:trainer_pokemon_id', to: 'trainers#remove_pokemon', as: 'remove_pokemon' 
  end
  resources :pokedexes
  resources :pokemons do
    get :new_details, on: :new
    post :add_skill
    get :heal
    post '/remove_skill/:pokemon_skill_id', to: 'pokemons#remove_skill', as: 'remove_skill'
    collection do
      get :heal_all
    end
  end
  
  resources :skills
  resources :pokemon_battles, only: [:index, :show, :new, :create] do
    get :auto_battle
    get :evolution_confirmation
    get :choose_skill
    post :submit_skill
    post :evolve
    post :action
    resources :pokemon_battle_logs, only: :index
  end
end

app/models/trainer.rb
class Trainer < ApplicationRecord
	has_many :trainer_pokemons, dependent: :destroy
	has_many :pokemon, through: :trainer_pokemons

	validates :name, presence: true,
						length: { maximum: 45 }
	validates :email, presence: true,
					  length: { maximum: 45 },
					  uniqueness: { case_sensitive: false },
					  format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController

	add_breadcrumb "Trainers", :trainers_path

	def index
		decorator = TrainersDecorator.new(self)
		@decorated_trainers = decorator.decorate_for_index(Trainer.paginate(page: params[:page], per_page: 10).order(id: :ASC))
		@pagination_trainers = Trainer.paginate(page: params[:page], per_page: 10).order(id: :ASC)
	end

	def show
		decorator = TrainersDecorator.new(self)
		@decorated_trainer = decorator.decorate_for_show(Trainer.find(params[:id]))
		@trainer_pokemon = TrainerPokemon.new
		add_breadcrumb @decorated_trainer.name
	end

	def new
		@trainer = Trainer.new
		add_breadcrumb 'New'
	end

	def edit
		@trainer = Trainer.find(params[:id])
		add_breadcrumb @trainer.name, @trainer
		add_breadcrumb 'Edit'
	end

	def create
		@trainer = Trainer.new(trainer_params)

		if @trainer.save
			redirect_to @trainer
		else
			render 'new'
		end
	end

	def update
		@trainer = Trainer.find(params[:id])

		if @trainer.update(trainer_params)
			redirect_to @trainer
		else
			render 'edit'
		end
	end

	def destroy
		@trainer = Trainer.find(params[:id])
		@trainer.destroy

		redirect_to trainers_path
	end

	def add_pokemon
		trainer = Trainer.find(params[:trainer_id])
		pokemon = Pokemon.find_by(id: params[:trainer_pokemon][:pokemon_id])
		@trainer_pokemon = TrainerPokemon.new(trainer: trainer, pokemon: pokemon)

		decorator = TrainersDecorator.new(self)
		@decorated_trainer = decorator.decorate_for_show(trainer)

		if @trainer_pokemon.save
			redirect_to trainer
		else
			render 'show'
		end
	end

	def remove_pokemon
		TrainerPokemon.find(params[:trainer_pokemon_id])
									.destroy

		redirect_to trainer_path(params[:trainer_id])
	end

	private
		def trainer_params
			params.require(:trainer).permit(:name, :email)
		end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<div class="panel-body">
	<div class="col-sm-offset-2 col-sm-8">
		<%= form_for @trainer do |f| %>
			<%= render 'layouts/error_message', error_object: @trainer.errors %>

			<div class="form-group <%= 'has-error' if @trainer.errors.include?(:name) %>">
				<%= f.label :name %>
	    	<%= f.text_field :name, class: 'form-control' %>
	    	<p class="error-message"><%= @trainer.errors.messages[:name].join(' and ') %></p>
			</div>
			<div class="form-group <%= 'has-error' if @trainer.errors.include?(:email) %>">
				<%= f.label :email %>
	    	<%= f.text_field :email, class: 'form-control' %>
	    	<p class="error-message"><%= @trainer.errors.messages[:email].join(' and ') %></p>
			</div>
			<%= f.submit yield(:submit_text), class: 'btn btn-primary center-block' %>
		<% end %>
	</div>
</div>

app/views/trainers/edit.html.erb
<% provide(:submit_text, 'Update') %>

<div class="panel panel-primary">
	<div class="panel-heading">Edit Trainer</div>
	<%= render 'trainers/form' %>
</div>

app/views/trainers/index.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Trainers</div>
	<div class="panel-body">
		<div class="action-container">
			<a href="<%= new_trainer_path %>" class="btn btn-primary">New</a>
		</div>
		<div class="col-xs-12 table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<td>#</td>
						<td>Name</td>
						<td>Email</td>
					</tr>
				</thead>
				<tbody>
					<%	if params[:page].to_i > 0 
								@current_page = (params[:page].to_i - 1) * 10
							else
								@current_page = params[:page].to_i * 10
							end
					%>
					<% @decorated_trainers.each_with_index do |trainer, index| %>
						<tr>
							<td><%= @current_page + index + 1 %></td>
							<td><%= trainer.link_to_show %></td>
							<td><%= trainer.email %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<div class="text-center flickr_pagination">
				<%= will_paginate @pagination_trainers %>
			</div>
		</div>
	</div>
</div>

app/views/trainers/new.html.erb
<% provide(:submit_text, 'Create') %>

<div class="panel panel-primary">
	<div class="panel-heading">New Trainer</div>
	<%= render 'trainers/form' %>
</div>

app/views/trainers/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Trainer</div>
	<div class="panel-body">
		<div class="col-sm-12 action-container">
			<a href="<%= new_trainer_path %>" class="btn btn-primary">New</a>
			<%= @decorated_trainer.link_to_edit %>
			<%= @decorated_trainer.link_to_delete %>
		</div>

		<div class="container action-container">
			<br><br>
			<table align="left">
				<tr>
					<td>Name</td>
					<td>&nbsp;:&nbsp;</td>
					<td><%= @decorated_trainer.name %></td>
				</tr>
				<tr>
					<td>Email</td>
					<td>&nbsp;:&nbsp;</td>
					<td><%= @decorated_trainer.email %></td>
				</tr>
			</table>
		</div>

		<div class="container col-sm-12">
			<div class="row">
				<h4>Pokemons</h4>
			</div>
			<div class="row">
				<table class="table table-hover">
					<thead>
						<tr>
							<td>#</td>
							<td>Name</td>
							<td>Level</td>
							<td>Battle Count</td>
							<td align="right">Action</td>
						</tr>
					</thead>
					<tbody>
						<% @decorated_trainer.trainer_pokemons.each_with_index do |trainer_pokemon, index| %>
							<tr>
								<td><%= index + 1 %></td>
								<td><%= link_to trainer_pokemon.name, pokemon_path(trainer_pokemon.pokemon_id) %></td>
								<td><%= trainer_pokemon.level %></td>
								<td><%= trainer_pokemon.count %></td>
								<td align="right"><%= link_to 'Remove', trainer_remove_pokemon_path(@decorated_trainer.id, trainer_pokemon.id),
										method: :post, 
										data: { confirm: "Are you sure to remove #{trainer_pokemon.name}?"}, class: 'btn btn-danger' %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>

		<div class="container col-sm-6">
			<h4>Add New Pokemon</h4>
			<%= form_for @trainer_pokemon, url: trainer_add_pokemon_path(@decorated_trainer.id) do |f| %>
				<%= render 'layouts/error_message', error_object: @trainer_pokemon.errors %>
				<div class="col-sm-12 form-group <%= 'has-error' if @trainer_pokemon.errors.include?(:pokemon) %>">
					<%= f.label :pokemon_id %>
					<%= f.select :pokemon_id, options_for_select(@decorated_trainer.pokemons_to_add.collect{ |pokemon| [pokemon.name, pokemon.id] }), { prompt: '-- Select --'}, {class: 'form-control'} %>
		    	<p class="error-message"><%= @trainer_pokemon.errors.messages[:pokemon].join(' and ') %></p>
				</div>
				<div class="col-sm-12 form-group">
					<%= f.submit :submit, class: 'btn btn-primary' %>
				</div>
			<% end %>
		</div>

		<% if @decorated_trainer.battle_count > 0 %>
			<div id="pie-chart-container" class="col-sm-6"></div>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	$(function () {
    $('#pie-chart-container').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            name: 'Battle Usage Percentage',
            colorByPoint: true,
            data: <%= raw @decorated_trainer.chart.to_json %>
        }]
    });
	});
</script>