config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  resources :trainers do
    post :add_pokemon
    post '/remove_pokemon/:trainer_pokemon_id', to: 'trainers#remove_pokemon', as: 'remove_pokemon' 
  end
  resources :pokedexes
  resources :pokemons do
    get :new_details, on: :new
    post :add_skill
    get :heal
    post '/remove_skill/:pokemon_skill_id', to: 'pokemons#remove_skill', as: 'remove_skill'
    collection do
      get :heal_all
    end
  end
  
  resources :skills
  resources :pokemon_battles, only: [:index, :show, :new, :create] do
    get :auto_battle
    get :evolution_confirmation
    get :choose_skill
    post :submit_skill
    post :evolve
    post :action
    resources :pokemon_battle_logs, only: :index
  end
end

app/views/layouts/_error_message.html.erb
<% if error_object.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <div>
      <h3>The form contains <%= pluralize(error_object.count, "error") %>.</h3>
    </div>
    <ul>
    <% error_object.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <p class="text-center">Created by : Riady</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<a href="<%= root_path %>" class="navbar-brand"><img src="http://images.ttcdn.co/media/i/product/349341-4daff8489eb34948851ec973240fde19.png"></a>

			<button type="button" class="navbar-toggle" data-toggle='collapse' data-target='.navbar-collapse'>
				<span class="sr-only">Toggle navigation</span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
			</button>
		</div>

		<ul class="nav navbar-nav navbar-right collapse navbar-collapse">
			<li><a href="<%= trainers_path %>">Trainer</a></li>
			<li><a href="<%= pokedexes_path %>">Pokedex</a></li>
			<li><a href="<%= pokemons_path %>">Pokemon</a></li>
			<li><a href="<%= skills_path %>">Skill</a></li>
			<li><a href="<%= pokemon_battles_path %>">Pokemon Battle</a></li>
		</ul>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonRainbow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= javascript_include_tag 'application' %>
  	<%= render 'layouts/header' %>
    <div class="container">
  		<div class="row">
        <div class="breadcrumb">
          <%= render_breadcrumbs :separator => ' / ' %>
        </div>
	  		<%= yield %>
  		</div>
  	</div>
  	<%= render 'layouts/footer' %>
  </body>
</html>